# Generated by Django 3.2.5 on 2021-07-07 03:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_catalog',
            fields=[
                ('CATE_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='location_catalog',
            fields=[
                ('LOC_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_product', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='measured_catalog',
            fields=[
                ('MEA_id', models.IntegerField(primary_key=True, serialize=False)),
                ('measured_catalog', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stocktaking_tb',
            fields=[
                ('SKU_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description_product', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_product', models.CharField(blank=True, max_length=20, null=True)),
                ('final_price_list', models.FloatField()),
                ('quantity_product', models.FloatField()),
                ('expiration_date', models.DateField()),
                ('agregation_date', models.DateField(default=datetime.date.today)),
                ('lastupdated_date', models.DateField(auto_now=True)),
                ('cost_unit', models.FloatField()),
                ('CATE_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.category_catalog')),
                ('LOC_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.location_catalog')),
                ('MEA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.measured_catalog')),
            ],
        ),
    ]
