# Generated by Django 3.2.4 on 2021-06-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalog_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATE_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stocktaking_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU_id', models.CharField(max_length=20)),
                ('CATE_id', models.IntegerField()),
                ('description_product', models.CharField(max_length=100)),
                ('brand_product', models.CharField(max_length=20)),
                ('list_price', models.FloatField()),
                ('quantity_product', models.FloatField()),
                ('measured_unit', models.CharField(max_length=10)),
                ('status_product', models.CharField(max_length=20)),
                ('expiration_date', models.DateField()),
                ('agregation_date', models.DateField()),
                ('cost_unit', models.FloatField()),
            ],
        ),
    ]
