version: '3.9'

services: 
    db:
        image: postgres
        volumes: 
            - ./data/db:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 10
        stop_grace_period: 60s

    web:
        build: .
        command: > 
            /bin/bash -c "chmod +x setsuperuser.sh
            && ./setsuperuser.sh"
        volumes: 
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            db:
              condition: service_healthy
        expose: 
            - "8000"

    nginx:
        build: ./nginx
        ports:
            - 1300:80
        depends_on: 
            - web
        restart: "on-failure"